steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build-ui-root
    args:
      - 'build'
      - '--no-cache'
      - '--file=./Dockerfile'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/voc-ui-root:$SHORT_SHA'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/voc-ui-root:latest'
      - '.'
    waitFor: ['-']
  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: push-ui-root
    args:
      - 'push'
      - 'eu.gcr.io/$PROJECT_ID/voc-ui-root:$SHORT_SHA'
    wait_for: ['build-ui-root']
  - name: 'gcr.io/cloud-builders/docker'
    id: push-ui-root-latest
    args:
      - 'push'
      - 'eu.gcr.io/$PROJECT_ID/voc-ui-root:latest'
    wait_for: ['build-ui-root']
  - name: 'gcr.io/cloud-builders/kubectl'
    id: deploy-ui-root-latest
    args:
      - 'set'
      - 'image'
      - 'deployment/ui-root-deployment'
      - 'ui-root=eu.gcr.io/$PROJECT_ID/voc-ui-root:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=voc-cluster-1'
    wait_for: ['push-ui-root']

  # [START cloudbuild-trigger-cd]
  # This step clones the ui-root-env repository
  - name: 'gcr.io/cloud-builders/gcloud'
    id: clone_env_repository
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        gcloud source repos clone ui-root-env && \
        cd ui-root-env && \
        git checkout candidate && \
        git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
    wait_for: ['push-ui-root']

  # This step generates the new manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    id: generate_manifest
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.yaml.tpl | \
        sed "s/COMMIT_SHA/${SHORT_SHA}/g" > ui-root-env/kubernetes.yaml
    wait_for: ['clone_env_repository']

  # This step pushes the manifest back to ui-root-env
  - name: 'gcr.io/cloud-builders/gcloud'
    id: push_manifest
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        cd ui-root-env && \
        git add kubernetes.yaml && \
        git commit -m "Deploying image eu.gcr.io/$PROJECT_ID/voc-ui-root:${SHORT_SHA}
        Built from commit ${COMMIT_SHA} of repository ui-root
        Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
        git push origin candidate
    wait_for: ['generate_manifest']

# [END cloudbuild-trigger-cd]
images:
  - 'eu.gcr.io/$PROJECT_ID/voc-ui-root:latest'
timeout: '1800s'