apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-root-deployment
  labels:
    app: ui-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-root
  template:
    metadata:
      labels:
        app: ui-root
    spec:
      containers:
        - name: ui-root
          image: eu.gcr.io/vote-of-confidence-233210/voc-ui-root:latest
          ports:
            - name: nginx-http
              containerPort: 8080
          resources:
            requests:
              cpu: 50m